# Generated by Django 3.2.3 on 2024-09-24 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_in_shopping_cart',
            field=models.ManyToManyField(related_name='in_cart_of_users', to=settings.AUTH_USER_MODEL, verbose_name='список покупок'),
        ),
    ]
